FROM grafana/grafana-oss:latest as grafana
COPY grafana.ini /etc/grafana/grafana.ini
RUN pwd
RUN ls -la
RUN ls -la conf
#RUN ls -la conf/provisioning
#RUN ls -la conf/provisioning/datasources
#RUN cat conf/provisioning/datasources/sample.yaml
#COPY supervisor.yaml conf/provisioning/datasources/supervisor.yaml
#COPY supervisor.yaml conf/provisioning/datasources/sample.yaml
