{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Supervision Hierarchy",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 21, "w": 11, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {},
    {},
    {},
    {}
   ]
  },
  {
   "title": "Processed Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "caf_system_processed_messages_total{instance=\"application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAF System Running Actors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "caf_system_running_actors{instance=\"application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "caf_system_rejected_messages_total{instance=\"application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}